apiVersion: apps/v1
kind: Deployment
metadata:
  name: sewan-go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: sewan-go-app
  template:
    metadata:
      labels:
        name: sewan-go-app
    spec:
      containers:
      - name: application
        image: emixbal/sewan-go:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
        env:
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "root"
          - name: DB_PORT
            value: "3306"
          - name: DB_HOST
            value: "sewan-go-mysql"
          - name: DB_NAME
            value: "sejutacita_api"