apiVersion: v1                           # API version
kind: Service                            # Type of kubernetes resource 
metadata:
  name: sewan-go-mysql                  # Name of the resource
  labels:                                # Labels that will be applied to the resource
    app: sewan-go-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:                              # Selects any Pod with labels `app=sewan-go-mysql,tier=mysql`
    app: sewan-go-mysql
    tier: mysql 